### ISSUE TITLE
assertion failed: phase_set.is_none()

### ISSUE THREAD

**Issue by ztdy** [PacificBiosciences/pb-StarPhase#27]
When using pbstarphase for data analysis, I encounter an error: "assertion failed: phase_set.is_none()". However, if I exclude the genes CYP2C19 and VKORC1, the analysis works fine. Can you please help me with this?

 LOG as below:

> [2024-08-02T10:48:45.217Z INFO  pbstarphase::cli::diplotype] Inputs:
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Database: "/home/bioinfo/db/module/pbstarphase/0.13.0/pbstarphase_20240730.json.gz"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Reference: "../inputs/401847941/human_GRCh38_no_alt_analysis_set.fasta"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    VCF: "../inputs/1274117384/WGSYJS.GRCh38.sentieon.phased.vcf.gz"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    BAM: "../inputs/1274117384/WGSYJS.GRCh38.haplotagged.bam"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Exclude set file: "exclude.gene.txt"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype] Outputs:
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Diplotype calls: "WGSYJS.pbstarphase.json"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    PharmCAT TSV: "WGSYJS.pharmcat.tsv"
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype] HLA settings:
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Max read error rate: 0.07
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Minimum CDF probability: 0.001
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype] CYP2D6 settings:
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Connection inferrence: DISABLED
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Normalize D6 only: DISABLED
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype] Consensus settings:
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Minimum consensus fraction: 0.1
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Minimum consensus count: 3
> [2024-08-02T10:48:45.221Z INFO  pbstarphase::cli::diplotype]    Dual max edit distance delta: 100
> [2024-08-02T10:48:45.221Z INFO  pbstarphase] Loading PGx database from "/home/bioinfo/db/module/pbstarphase/0.13.0/pbstarphase_20240730.json.gz"...
> [2024-08-02T10:48:48.488Z INFO  pbstarphase] Loading reference genome from "../inputs/401847941/human_GRCh38_no_alt_analysis_set.fasta"...
> [2024-08-02T10:48:57.604Z INFO  pbstarphase::diplotyper] Solving ABCG2...
> [2024-08-02T10:48:57.687Z INFO  pbstarphase::diplotyper] Solving CACNA1S...
> [2024-08-02T10:48:57.751Z INFO  pbstarphase::diplotyper] Solving CFTR...
> [2024-08-02T10:48:57.902Z INFO  pbstarphase::diplotyper] Solving CYP2B6...
> [2024-08-02T10:48:58.042Z INFO  pbstarphase::diplotyper] Solving CYP2C9...
> [2024-08-02T10:48:58.269Z INFO  pbstarphase::diplotyper] Solving CYP3A5...
> [2024-08-02T10:48:58.342Z INFO  pbstarphase::diplotyper] Solving CYP4F2...
> [2024-08-02T10:48:58.426Z INFO  pbstarphase::diplotyper] Solving DPYD...
> [2024-08-02T10:48:58.551Z INFO  pbstarphase::diplotyper] Solving G6PD...
> [2024-08-02T10:48:58.551Z WARN  pbstarphase::diplotyper] Error while normalizing database variant 778641: At chrX:154532438, provided reference allele has "G" but reference genome has "A", PgxVariant { name: "c.1311C>T", dbsnp_id: Some("rs2230037"), position: 154532439, alleles: [Some("G"), Some("A")] }
> [2024-08-02T10:48:58.551Z WARN  pbstarphase::diplotyper] Ignoring "Mediterranean Haplotype" due to variant incompatibility.
> [2024-08-02T10:48:58.816Z INFO  pbstarphase::diplotyper] Solving IFNL3...
> [2024-08-02T10:48:58.877Z INFO  pbstarphase::diplotyper] Solving MT-RNR1...
> [2024-08-02T10:48:58.877Z WARN  pbstarphase::diplotyper] Error while normalizing database variant 828080: At chrM:929, provided reference allele has "A" but reference genome has "G", PgxVariant { name: "930A>G", dbsnp_id: None, position: 930, alleles: [Some("A"), Some("G")] }
> [2024-08-02T10:48:58.877Z WARN  pbstarphase::diplotyper] Ignoring "m.930A>G" due to variant incompatibility.
> [2024-08-02T10:48:58.953Z INFO  pbstarphase::diplotyper] Solving NUDT15...
> [2024-08-02T10:48:59.115Z INFO  pbstarphase::diplotyper] Solving RYR1...
> [2024-08-02T10:48:59.722Z INFO  pbstarphase::diplotyper] Solving SLCO1B1...
> [2024-08-02T10:48:59.850Z INFO  pbstarphase::diplotyper] Solving TPMT...
> [2024-08-02T10:49:00.056Z INFO  pbstarphase::diplotyper] Solving UGT1A1...
> [2024-08-02T10:49:00.126Z INFO  pbstarphase::diplotyper] Solving VKORC1...
> thread 'main' panicked at src/diplotyper.rs:437:41:
> assertion failed: phase_set.is_none()
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
>    1: core::panicking::panic_fmt
>              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
>    2: core::panicking::panic
>              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
>    3: pbstarphase::diplotyper::call_diplotypes
>    4: pbstarphase::main
>

**Comment by holtjma** [comment]
Hi @ztdy,

I can at least explain how the assertion is triggering:

1. StarPhase is searching for a set of variants in your VCF file and normalizing them to match the variants in the database.
2. Inside this code block, it identified a homozygous variant that matches one of the variants in the database.
3. One of the assertions for a homozygous variant is that there is no phase set (PS tag) tied to it. Intuitively, this is because a homozygous variant doesn't have a phase, it's on both alleles.

So it seems like it's identifying a variant in your dataset that is A) homozygous and B) for some reason has a phase set.  Are you using something other than DeepVariant/HiPhase for your variant calling and phasing? I've never seen this situation happen with those.

Matt

**Comment by ztdy** [comment]
Hi @holtjma 

Thank you for your response. 

You are correct. I used Sentieon for variant calling, followed by HiPhase for phasing, and finally used pbstarphase. 

In the current situation, do I have any way to solve this problem by removing the homozygous PS tags?

**Comment by ztdy** [comment]
Hi holtjma,

Due to the large size of the original VCF file, I extracted data for chr10/chr16. For the VKORC1 gene, there are indeed homozygous variants with the PS tag.


[chr10.chr16.vcf.gz.zip](https://github.com/user-attachments/files/16476981/chr10.chr16.vcf.gz.zip)

**Comment by holtjma** [comment]
Right, I see your file now.  So here is my running hypothesis: I suspect that Sentieon is outputting some phase set tags for you already (I don't know why, but I imagine you can ask the developers at Sentieon). If you run this command, you will get a lot of homozygous variants that are seemingly "phased" with this PS tag, an example is below (truncated):

```
$ gunzip -c chr10.chr16.vcf.gz | grep "31079607"
chr16	31063854	.	G	A	476.83	.	AC=2;AF=1;AN=2;DP=11;Entropy=0.69;ExcessHet=3.0103;FS=0;GC=64.81;MLEAC=2;MLEAF=1;ML_PROB=0;MQ=60;NBQ=76.289;QD=43.35;ReadPosEndDist=67.909;SOR=1.802;UDP=11	GT:AD:DP:GQ:PL:PS	1|1:0,11:11:33:495,33,0:31079607
...
```

However, in the middle of that group, you also get the original heterozygous variant at that position (which is usually how a PS tag gets identified):
```
chr16	31079607	.	C	T	137.83	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-0.566;ClippingRankSum=-0;DP=8;Entropy=0.4;ExcessHet=3.0103;FS=3.136;GC=62.95;MLEAC=1;MLEAF=0.5;ML_PROB=0;MQ=60;MQRankSum=-0;NBQ=72.977;QD=17.23;ReadPosEndDist=20;ReadPosRankSum=-0;SOR=1.447;UDP=8	GT:AD:DP:GQ:PL:PS	1|0:4,4:8:99:156,0,213:31056866
```

Note that the heterozygous variant there has a **different** PS tag of **31056866**, which was likely generated and overwritten by HiPhase.  However, HiPhase will not strip out pre-existing phase information from other entries that it does not phase, leaving all these extra fields in those homozygous variants surround it.

There's a couple key points I want to make here:
1. This _definitely_ is not supported by StarPhase, so we likely will not be making any changes aside from possibly improving the error message to make it clear what the issue is instead of a panic.
2. As the main developer of HiPhase, this is also incorrect usage for HiPhase.  If you do not strip all phase information prior to running the tool, HiPhase will not strip that information either, and you get a VCF file that has a mixture of PS tags leading to difficult and/or meaningless phase set information that cannot be easily or accurately interpreted.  I strongly recommend removing **all** phasing and phase set tags prior to running HiPhase.

Matt

**Comment by ztdy** [comment]
I am using the sentieon-cli workflow, which includes the phasing feature. Now I have switched to the original sentieon command line. It appears that pbstarphase is working normally now. Thank you for resolving the issue.
